### GET all jewels
GET http://localhost:3000/jewels


### GET single jewel
GET http://localhost:3000/jewels/692712f5b025079a15b10d4a



### POST - Create new jewel
POST http://localhost:3000/jewels
Content-Type: application/json

{
  "name": "Diamond Ring",
  "type": "Ring",
  "price": 1500,
  "carat": 2,
  "description": "A beautiful diamond ring."
}


### PUT - Update jewel (replace all fields)
PUT http://localhost:3000/jewels/692712f5b025079a15b10d4a
Content-Type: application/json

{
  "name": "Updated Diamond Ring",
  "type": "Ring",
  "price": 1800,
  "carat": 2.5,
  "description": "Updated description"
}


### DELETE - Delete jewel
DELETE http://localhost:3000/jewels/692712f5b025079a15b10d4a
